# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - southern-cars-erp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: api - yarn install, build and start
        run: |
          cd api
          yarn
          yarn start

      - name: web - yarn install, build and start
        run: |
          cd web
          yarn
          yarn build
          serve -s build

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "southern-cars-erp"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5a59bed1f20e49b8bfbef7bef4a61ecb }}
          package: .
